app/urls.py
from django.urls import path
from app.views import ItemTemplate, BuyApi, ItemsPage, success_page, cancel_page

urlpatterns = [
	path('', ItemsPage.as_view(), name='home'),
	path('cancel/', cancel_page, name='cancel'),
	path('success/', success_page, name='success'),
	path('buy/<int:id>', BuyApi.as_view(), name='buy'),
	path('item/<int:pk>', ItemTemplate.as_view(), name='item'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('v1/app/', include(('app.urls', 'app'), namespace='app')),
]

app/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.

class BaseModel(models.Model):
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	class Meta:
		abstract = True


class Item(BaseModel):
	name = models.CharField(max_length=50)
	description = models.TextField()
	price = models.DecimalField(default=0, max_digits=10, decimal_places=2)


	def __str__(self):
		return self.name

	class Meta:
		verbose_name = 'Item'
		verbose_name_plural = 'Items'


class Order(BaseModel):
	total_price = models.DecimalField(default=0, max_digits=12, decimal_places=2)

	order = models.ForeignKey('Discount', models.CASCADE, related_name='orders', related_query_name='orders')
	tax = models.ForeignKey('Tax', models.CASCADE, related_name='orders', related_query_name='orders')
	item = models.ForeignKey('Item', models.CASCADE, related_name='orders', related_query_name='orders')



	class Meta:
		verbose_name = 'Order'
		verbose_name_plural = 'Orders'


class Discount(BaseModel):
	percentage = models.IntegerField(validators=[
			MaxValueValidator(100),
			MinValueValidator(0)
		])

	class Meta:
		verbose_name = 'Discount'
		verbose_name_plural = 'Discounts'


class Tax(BaseModel):
	percentage = models.IntegerField(validators=[
			MaxValueValidator(100),
			MinValueValidator(0)
		])

	class Meta:
		verbose_name = 'Tax'
		verbose_name_plural = 'Taxes'

app/views.py
from django.shortcuts import render, redirect
# from rest_framework.views import APIView
from django.views import View
from app.models import Item
from django.shortcuts import get_object_or_404
from django.conf import settings
import stripe



class ItemsPage(View):
	template_name = 'home.html'

	def get(self, request):
		items = Item.objects.all()
		return render(request, self.template_name, {'items': items})


class BuyApi(View):

	def get(self, request, id):
		item = get_object_or_404(Item, pk=id)

		stripe.api_key = settings.STRIPE_API_KEY

		session = stripe.checkout.Session.create(
				line_items=[{
			      	'price_data': {
			        	'currency': 'usd',
			        	'product_data': {
			        		  'name': item.name,
		        			},
			        	'unit_amount': int(item.price),
			      	},
			      	'quantity': 1,
			    }],
			    mode='payment',
			    success_url='http://localhost:8000/v1/app/success',
			    cancel_url='http://localhost:8000/v1/app/cancel',
			)

		return redirect(session.url, code=303)

		# session =stripe.PaymentIntent.create(
		# 	  amount=int(item.price),
		# 	  currency="usd",
		# 	  description=item.description,
		# 	  automatic_payment_methods={"enabled": True}
		# 	)

		# print(session)


class ItemTemplate(View):
	template_name = "item.html"

	def get(self, request, pk):
		item = get_object_or_404(Item, pk=pk)
		return render(request, self.template_name, {'item': item})


def success_page(request):
	return render(request, 'success.html', {'info': None})


def cancel_page(request):
	return render(request, 'cancel.html', {'info': None})

app/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	{% block title %}{% endblock title %}
</head>
<body>
	{% block content %}{% endblock content %}

	{% block script %}{% endblock script %}
</body>
</html>

app/templates/cancel.html
{% extends 'base.html' %}

{% block title %}
	<title>Thanks for your order!</title>
{% endblock title %}

{% block content %}
	<div>
		<h1>Purchase has been cancelled.</h1>
	    <p>
	      If you have any questions, please contact the administration!
	      <a href="mailto:admin@admin.com">admin@admin.com</a>.
	      <br>
	      <a href="{% url 'app:home' %}">Go to home page</a>.
	    </p>
	</div>
{% endblock content %}

app/templates/home.html
{% extends 'base.html' %}

{% block title %}
	<title>Django+stripe</title>
{% endblock title %}

{% block content %}
	<div>
		{% for item in items %}
			<div>
				<h1>#{{ item.pk }} {{ item.name }}</h1>
				<p>{{ item.description }}</p>
				<a href="{% url 'app:item' item.pk %}">read more</a>
			</div>
		{% endfor %}
	</div>
{% endblock content %}

app/templates/item.html
{% extends 'base.html' %}

{% block content %}
	<div>
		<h1>#{{ item.pk }} {{ item.name }}</h1>
		<p>{{ item.description }}</p>
		<p>{{ item.price }} USD</p>
		<form action="{% url 'app:buy' item.pk %}" method="GET">
			<button>Купить!</button>
		</form>
	</div>
{% endblock content %}

app/templates/success.html
{% extends 'base.html' %}

{% block title %}
	<title>Thanks for your order!</title>
{% endblock title %}

{% block content %}
	<div>
		<h1>Thanks for your order!</h1>
	    <p>
	      We appreciate your business!
	      If you have any questions, please email
	      <a href="mailto:admin@admin.com">admin@admin.com</a>.
	      <br>
	      <a href="{% url 'app:home' %}">Go to home page</a>.
	    </p>
	</div>
{% endblock content %}